### ISSUE TITLE
'era_test_node fork testnet' gives Version14 error

### ISSUE THREAD

**Issue by deanpress** [matter-labs/era-test-node#109]
#### 📝 Description
Following the installation instructions and then running `era_test_node fork testnet` results in the following error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError(Error("unknown variant `Version14`, expected one of 
`Version0`, `Version1`, `Version2`, `Version3`, `Version4`, `Version5`, `Version6`, `Version7`, `Version8`, `Version9`, `Version10`, `Version11`, `Version12`, `Version13`", line: 1, column: 641))', src/fork.rs:237:14
```

#### 🔄 Reproduction Steps

1. Step 1: fresh install of in-memory node
2. Step 2: run era_test_node fork testnet

#### 🖥️ Environment

- **Rust version**: 1.72.0
- **Operating System & Version**: Ubuntu 20.04 (WSL)

**Comment by artemmartyhin** [comment]
> Confirmed this is an issue, but unfortunately the only solution is to either pass in a specific block head to fork from (ex: `--fork-at 7000000`) or wait until the upstream `zksync-era` repo has been updated with the latest `Version14`.

Such approach causes the same result with Version14
era_test_node fork mainnet --fork-at 13800000

**Comment by nbaztec** [comment]
The cutoff seems to the block `13234790`. Anything above it will fail.

**Comment by artemmartyhin** [comment]
> The cutoff seems to the block `13234790`. Anything above it will fail.

Same error even using higher block number
`era_test_node fork mainnet --fork-at 13235000`

**Comment by AaronNan24** [comment]
any updates or fix on this?

**Comment by MexicanAce** [comment]
@AaronNan24 We're still waiting on an upstream change to be pushed to `zksync-era`. Once that's merged, this PR should address the problem: https://github.com/matter-labs/era-test-node/pull/111

**Comment by AaronNan24** [comment]
Thx ur efforts! @MexicanAce 

Would like to know how to use it ahead of time, can I build it locally to use? or is there any way to replay an existing transaction. I did use `zkcast`, but it also had problems, so I failed

wanted to look at the existing transactions to troubleshoot the code issue, thank you very much for your generous assistance!

**Comment by MexicanAce** [comment]
Unfortunately there's no work around until `zksync-era` is updated with the latest code running in Testnet/Mainnet. This is expected to happen before the end of the week.

**Comment by AaronNan24** [comment]
appreciate ur quick reply and explanation! and thanks again for all your hard work and shoutout to you guys

**Comment by MexicanAce** [comment]
This has been resolved with the latest Release and #111

**Comment by AaronNan24** [comment]
Big thanks! @MexicanAce 
btw, how to upgrade existing era_test_node you recommend

**Comment by MexicanAce** [comment]
Here's the latest release with the binaries: https://github.com/matter-labs/era-test-node/releases/latest
