### ISSUE TITLE
Error Installing test-node with Mac (Intel CPU)

### ISSUE THREAD

**Issue by Gilgamesh-818** [matter-labs/era-test-node#14]
When I run the cargo install command I'm getting a compile error stating that the google-cloud-default package can not be found at 

https://github.com/yoshidan/google-cloud-rust?branch=main

This is a dependency in the zksync_object_store package found in the zksync-era/core/lib repo. I'm currently trying to fix the issue locally by changing the dependency to the crate.io google-cloud-default created by yoshida. This fixes the dependency problem, but there are other errors thrown from the ClientConfig methods not being found in the gcs.rs file in the object_store's src directory. I think maybe the git google-cloud-rust fork has undergone some breaking changes and no longer works with the zksync implementation. I could be misunderstanding the issue though so some help and clarity on this would be greatly appreciated.

**Comment by mm-zk** [comment]
Yes, something has changed in the google-cloud-rust. Investigating.

**Comment by Gilgamesh-818** [comment]
Yes there was a recent change in the google-cloud-rust that deprecated the google-cloud-default package. I fixed this issue, then I encountered another compile time error with the zkevm-assembly package as regex::internal::Input can not be found. I deleted this import and now in my fork the era-test-node will compile and install.

**Comment by faheelsattar** [comment]
I am facing a similar issue on ubuntu. Any status on when this will be fixed?

**Comment by MexicanAce** [comment]
PR open that will address this issue: https://github.com/matter-labs/era-test-node/pull/15

Will close this thread once that PR is merged
