### ISSUE TITLE
BUG 🐛: Import "hardhat/console.sol" not working with latest era-test-node release

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#154]
## 📝 Description

After updating to the latest release of era-test-node, I noticed that the import statement import "hardhat/console.sol"; does not work as expected. This seems to prevent any console logs from being displayed when running tests. I believe the issue originates from the following commit: [915b0c0086173668a628d851e1a22430f74a2487](https://github.com/matter-labs/era-test-node/commit/915b0c0086173668a628d851e1a22430f74a2487).

### 🔄 Reproduction Steps

1. Clone the latest version of era-test-node.
2. Run `make rust-build`
3. Start the node `./target/release/era_test_node --log debug run`
4. In a new terminal window, change directory to `/e2e-tests`.
5. Run `yarn test`.
6. Observe no console logs will be present

### 🤔 Expected Behavior

Console logs should be displayed when running tests.

### 😯 Current Behavior

No console logs are displayed.

#### 🖥️ Environment

- **Rust version**: `rustc 1.73.0-nightly`
- **Operating System & Version**: macos

**Comment by MexicanAce** [comment]
After digging in, it looks like the `CallTracer` within `zksync-era` is not returning the call stack like we had been using with `vm.execute_till_block_end_with_call_tracer(BootloaderJobType::TransactionExecution);`. The only calls that are saved in the tracer are emit events.

Link to `CallTracer`: https://github.com/matter-labs/zksync-era/blob/main/core/lib/vm/src/tracers/call.rs

This is a huge setback for troubleshooting of Smart Contracts on era-test-node and has become a P0 to be addressed.

**Comment by MexicanAce** [comment]
This issue was resolved in the latest upstream changes from `zksync-era`. Will open a PR updating our reference accordingly
