### ISSUE TITLE
FEAT: Support additional console log payloads

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#156]
#### 📝 Description

era-test-node currently seems to only support `console.log` that is limited to specific types. If you try to make use of `console.logBytes(value1);` the output in the logs is as follows: 

<img width="673" alt="Screenshot 2023-10-03 at 9 06 46 AM" src="https://github.com/matter-labs/era-test-node/assets/29983536/67bfc752-b931-4372-b0fd-0c9ac9e2ed74">

It would be good for users to be able to log any type according to hardhat console log [here](https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-core/console.sol).

#### 🤔 Rationale

If I want to log bytes its easier to make use of `console.logBytes(value1);`.

**Comment by MexicanAce** [comment]
This will have performance impacts to investigate for anyone adding full support:
```rust
// We don't support all the log methods (for example hardhat supports all type combinations up to 4) - as this drastically increases the compilation time.
```
