### ISSUE TITLE
NFT Gated Paymasters do not work with era_test_node

### ISSUE THREAD

**Issue by MexicanAce** [matter-labs/era-test-node#166]
#### 📝 Description

Attempting to use an NFT Gated Paymaster with `era_test_node` throws an error when attempting to pay gas fees on the behalf of a user when they have the NFT.

Error from the UI:
![image](https://github.com/matter-labs/era-test-node/assets/1890113/493c97a8-a369-4bba-9441-322145916f5e)

Error from `era_test_node`:
```
13:42:01 [INFO] Call: SUCCESS
13:42:01 [INFO] Output: "0x0000000000000000000000000000000000000000000000000000000000000001"
13:42:01 [INFO] === Console Logs: 
13:42:01 [INFO] === Call traces:
13:42:18 [INFO] Unable to estimate gas for the request with our suggested gas limit of 84225845. The transaction is most likely unexecutable. Breakdown of estimation:
13:42:18 [INFO]         Estimated transaction body gas cost: 80000000
13:42:18 [INFO]         Gas for pubdata: 0
13:42:18 [INFO]         Overhead: 4225845
13:42:18 [INFO] execution reverted: virtual machine entered unexpected state. Please contact developers and provide transaction details that caused this error. Error description: Assertion error: paymaster non zero
```

#### 🔄 Reproduction Steps

1. Start node `era_test_node fork mainnet`
2. Clone repo : https://github.com/MexicanAce/misfits-and-magic
3. Install npm dependencies: `cd backend && npm install`
4. Compile contracts: `yarn compile`
5. Setup `.env` file with Rich Wallet Key and address of an NFT you have:
  - `WALLET_PRIVATE_KEY=0xe667e57a9b8aaa6709e51ff7d093f1c5b73b63f9987e4ab4aa9a5c699e024ee8`
  -  `ADDRESS_OF_NFT_COLLECTION_CONTRACT=0x1F13941D0995e111675124aF4B0F9bDcc70390C3`
6. Deploy contracts: `yarn deploy`
7. Start up the UI: `cd .. & npm run dev`
8. Connect to a wallet with the NFT and attempt to save the character by clicking `Upload Character` from the hamburger menu on the top-right, seeing that you don't have to pay because you have the NFT, and clicking `CONFIRM`:
![image](https://github.com/matter-labs/era-test-node/assets/1890113/b69d8361-3f62-457d-b517-1f591cdf299b)

#### 🤔 Expected Behavior

The NFT Gated Paymaster pays the fee for the user with no error

#### 😯 Current Behavior

Error is shown in the UI:
```
execution reverted: virtual machine entered unexpected state. Please contact developers and provide transaction details that caused this error. Error description: Assertion error: paymaster non zero
```

**Comment by dutterbutter** [comment]
Do you know if this occurs for all paymaster contracts?

**Comment by MexicanAce** [comment]
@dutterbutter Those tests never actually attempt to use the paymaster, and they would've caught this 👍 https://github.com/matter-labs/tutorials/blob/main/gated-nft/zksync/test/main.test.ts

**Comment by MexicanAce** [comment]
Sharing the other set of tests that you sent me @dutterbutter : https://github.com/matter-labs/paymaster-examples/blob/main/contracts/test/erc721gated.test.ts

**Comment by MexicanAce** [comment]
Found the problem, we're missing code in gas estimation when the transaction type is `None`. Will put up PR soon.
