### ISSUE TITLE
fork error

### ISSUE THREAD

**Issue by Ivory433** [matter-labs/era-test-node#181]
#### 📝 Description

fork cause error when i'm trying to fork from other network like https://rpc.ankr.com/zksync_era

#### 🔄 Reproduction Steps

1. era_Test_node fork https://rpc.ankr.com/zksync_era

#### 😯 Current Behavior

```
thread 'main' panicked at src/fork.rs:391:14:
Unable to create a client for fork: Transport(Invalid Url: Port number is missing in the URL)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

#### 🖥️ Environment

era_test_node 0.1.0-alpha.7

**Comment by MexicanAce** [comment]
Hi @Ivory433 , something like the following _should_ work:

```bash
era_test_node fork https://rpc.ankr.com:443/zksync_era
```

If you run into an error, try specifying a specific block you want to fork from with `--fork-at 14000000`
