### ISSUE TITLE
Missing web3_clientVersion API : tests not running

### ISSUE THREAD

**Issue by abdullah-txfusion** [matter-labs/era-test-node#188]
#### 📝 Description
I'm running tests for some smart contracts using the in-memory node setup. I'm having the issue mentioned below with one of the smart contracts, while others are working fine.

```
Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32601,\"message\":\"Method not 
found\"},\"id\":48}\n", error={"code":-32601}, requestBody="{\"method\":\"web3_clientVersion\",\"params\":
[],\"id\":48,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://127.0.0.1:8011", code=SERVER_ERROR, version=web/5.7.1)
```

Detailed log for `yarn test`:
```
 "before each" hook: Setting up the context for "should ...":
     Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32601,\"message\":\"Method not found\"},\"id\":48}\n", error={"code":-32601}, requestBody="{\"method\":\"web3_clientVersion\",\"params\":[],\"id\":48,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://127.0.0.1:8011", code=SERVER_ERROR, version=web/5.7.1)

at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
      at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
      at /Users/abdullah/Documents/code/work/TxTsuko/blockchain/node_modules/@ethersproject/web/src.ts/index.ts:341:28
      at step (node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (node_modules/@ethersproject/web/lib/index.js:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Here's the snippet of code where the test is crashing.
```
const Factory = await hre.zkUpgrades
    .deployProxy(deployer.zkWallet, FactoryArtifacts, [ZERO_ADDRESS])
    .then((r) => r.deployed());
```

#### 🔄 Reproduction Steps

1. `era_test_node run`
2. `yarn test`

#### 🤔 Expected Behavior

Tests should pass

#### 😯 Current Behavior

Tests are crashing

#### 🖥️ Environment

- **Rust version**: [rustc 1.73.0 (cc66ad468 2023-10-03)]
- **Operating System & Version**: [macOS 13.6 (22G120)]
- **Hardware**: [macbook pro 2020 intel i7]

#### 📎 Log Output
No logs in the in-memory node output

**Comment by MexicanAce** [comment]
It looks like you're calling `web3_clientVersion` and the `web3_` namespace is not implemented (yet) for the `era_test_node`.

**Comment by MexicanAce** [comment]
It's this function that's checking if you're deploying to a development network:
https://github.com/matter-labs/hardhat-zksync/blob/b3e345a79bc4d707b2f81876b03bb525b5323b14/packages/hardhat-zksync-upgradable/src/core/impl-store.ts#L152-L161

Note: We can implement `web3_clientVersion`, but `isDevelopmentNetwork(...)` in `hardhat-zksync-upgradable` will still return `False` as it's not one of the expected development networks. So we should return a unique value (e.g. `era-test-node`) and maybe also update `isDevelopmentNetwork()` in the hardhat plugin

**Comment by abdullah-txfusion** [comment]
Thanks! Is this an OS specific issue? Since the tests are crashing for me on macOS as mentioned in the issue, but they are working fine on Ubuntu. (no changes in code, config is same just the OS is different).

**Comment by MexicanAce** [comment]
The endpoint doesn't exist for any OS. So if this error is not occurring for macOS, perhaps the hardhat plugin behaves differently on per OS?

**Comment by abdullah-txfusion** [comment]
Thanks! I'll ask the team to investigate the issue and notice the behaviour across all operating systems. We'll keep you updated on our progress.
