### ISSUE TITLE
Terminal console log showing "Method get_transaction_by_hash is not implemented" message loop after sending transaction using Remix and Metamask.

### ISSUE THREAD

**Issue by ChroII0** [matter-labs/era-test-node#19]
Hello guys, Currently I am using era-test-node to fork mainnet and use it following these steps:
  1. Fork mainnet.
  2. Add RPC in Metamask.
  3. Use Remix and load a contract that may be available on the mainnet for testing.
  
The call methods are still working fine, but when I do **send transaction**. Although Metamask announced the transaction was successful, at this point Remix's console log still shows the transaction as pending and the terminal console log shows "**Method get_transaction_by_hash is not implemented**" message loop.

_I'm not sure this is era-test-node's fault, but I need your help._

**Comment by dutterbutter** [comment]
Thank you for exploring era-test-node 🚀  ! As we are presently in the Alpha phase, certain API endpoints, including `get_transaction_by_hash`, have not yet been fully implemented. The error you encountered is expected under current conditions. Rest assured, complete API support is on our priority list and we're actively working on it.

In the meantime, if you're comfortable contributing, we wholeheartedly welcome PRs to implement `get_transaction_by_hash`. Every contribution helps accelerate our journey to completion!

**Comment by ChroII0** [comment]
> 
Many thx bro, but my work is very busy, I will come back after era-test-node is more complete:clap:

**Comment by ChroII0** [comment]
> Thank you for exploring era-test-node 🚀 ! As we are presently in the Alpha phase, certain API endpoints, including `get_transaction_by_hash`, have not yet been fully implemented. The error you encountered is expected under current conditions. Rest assured, complete API support is on our priority list and we're actively working on it.
> 
> In the meantime, if you're comfortable contributing, we wholeheartedly welcome PRs to implement `get_transaction_by_hash`. Every contribution helps accelerate our journey to completion!

Oh, it seems that the error displaying the `Method get_transaction_by_hash is not implemented` message loop in Terminal only occurs when performing a transaction on **Remix**.
If only using Metamask it still works fine. However, there is another problem that if the transaction is reverted, the terminal will display a message loop of `thread 'tokio-runtime-worker' panicking at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', src/node.rs:668:44` and can no longer make calls or send transactions.
This can only be fixed by shutting down and restarting node. But will lose all the states that have interacted with the previous node and have to do it all over again.

**Comment by ChroII0** [comment]
> > Thank you for exploring era-test-node rocket ! As we are presently in the Alpha phase, certain API endpoints, including `get_transaction_by_hash`, have not yet been fully implemented. The error you encountered is expected under current conditions. Rest assured, complete API support is on our priority list and we're actively working on it.
> > In the meantime, if you're comfortable contributing, we wholeheartedly welcome PRs to implement `get_transaction_by_hash`. Every contribution helps accelerate our journey to completion!
> 
> Oh, it seems that the error displaying the `Method get_transaction_by_hash is not implemented` message loop in Terminal only occurs when performing a transaction on **Remix**.
> 
> If only using **Metamask** it still works fine. However, there is another problem that if the **`transaction is reverted`**, the terminal will display a message loop of `` thread 'tokio-runtime-worker' panicking at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', src/node.rs:668:44 `` and can no longer make calls or send transactions.
> 
> This can only be fixed by shutting down and restarting node. But will lose all the states that have interacted with the previous node and have to do it all over again.

Oh, maybe that error only occurs when making transactions that exceed the account's ETH balance. Everything else works fine, I'll close this issue here.
