### ISSUE TITLE
System crashes when executing transaction with gasLimit too large

### ISSUE THREAD

**Issue by Romsters** [matter-labs/era-test-node#206]
#### 📝 Description

When transaction has gasLimit larger than what U32 can contain the system crashes.

#### 🔄 Reproduction Steps

Set `gasLimit` to something like `ethers.utils.parseEther("0.1")` and send transaction.

#### 🤔 Expected Behavior

System should not crash and instead return an error `exceeds block gas limit`.

#### 😯 Current Behavior

System crashes when trying to convert gasLimit to U32.

#### 🖥️ Environment

- **Rust version**: 1.73.0
- **Operating System & Version**: macOS

#### 📎 Log Output

thread 'tokio-runtime-worker' panicked at /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/primitive-types-0.12.2/src/lib.rs:38:1:
Integer overflow when casting to u32
stack backtrace:
   0: rust_begin_unwind
             at /rustc/aa1a71e9e90f6eb3aed8cf79fc80bea304c17ecb/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/aa1a71e9e90f6eb3aed8cf79fc80bea304c17ecb/library/core/src/panicking.rs:72:14
   2: primitive_types::U256::as_u32
             at /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/uint-0.9.5/src/uint.rs:633:6
   3: multivm::versions::vm_virtual_blocks::types::internals::transaction_data::TransactionData::overhead_gas
             at /Users/user/.cargo/git/checkouts/zksync-era-657998444dcd9ed9/73a1e8f/core/lib/multivm/src/versions/vm_virtual_blocks/types/internals/transaction_data.rs:203:31
   4: multivm::versions::vm_virtual_blocks::implementation::tx::<impl multivm::versions::vm_virtual_blocks::vm::Vm<S,H>>::push_transaction_with_compression
             at /Users/user/.cargo/git/checkouts/zksync-era-657998444dcd9ed9/73a1e8f/core/lib/multivm/src/versions/vm_virtual_blocks/implementation/tx.rs:64:24
   5: multivm::versions::vm_virtual_blocks::vm::Vm<S,H>::push_transaction
             at /Users/user/.cargo/git/checkouts/zksync-era-657998444dcd9ed9/73a1e8f/core/lib/multivm/src/versions/vm_virtual_blocks/vm.rs:48:9
   6: era_test_node::node::InMemoryNode<S>::run_l2_tx_inner
             at ./src/node.rs:1289:9
   7: era_test_node::node::InMemoryNode<S>::run_l2_tx
             at ./src/node.rs:1471:13
   8: <era_test_node::node::InMemoryNode<S> as zksync_core::api_server::web3::backend_jsonrpc::namespaces::eth::rpc_impl_EthNamespaceT::gen_server::EthNamespaceT>::send_raw_transaction
             at ./src/node.rs:2019:15
   9: zksync_core::api_server::web3::backend_jsonrpc::namespaces::eth::rpc_impl_EthNamespaceT::gen_server::EthNamespaceT::to_delegate::{{closure}}
             at /Users/user/.cargo/git/checkouts/zksync-era-657998444dcd9ed9/73a1e8f/core/lib/zksync_core/src/api_server/web3/backend_jsonrpc/namespaces/eth.rs:23:1

**Comment by MexicanAce** [comment]
Addressed with #207
