### ISSUE TITLE
web3_clientVersion not implemented

### ISSUE THREAD

**Issue by StefanosChaliasos** [matter-labs/era-test-node#211]
#### 📝 Description

The endpoint `web3_clientVersion` is not implemented.

#### 🤔 Rationale

It is used by the `isConnected` method in the `Web3` library. Many clients use this method.

#### 🖼️ Mockups/Examples

Example `curl` request.

```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":1}' http://localhost:8011
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":1}
```

**Comment by MexicanAce** [comment]
Completed in #223
