### ISSUE TITLE
Panic on a transaction that doesn't pass the validation step

### ISSUE THREAD

**Issue by vladbochok** [matter-labs/era-test-node#23]
#### 📝 Description

Test node panics on submitting transaction which validation failed (e.g. not enough balance, incorrect nonce or signature). 

#### 🔄 Reproduction Steps

1. Run the node
2. Send valid transaction
3. Transaction would be executed correctly
4. Send the same transaction
5. Node panics with 

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ValidationFailed(General { msg: ...
```

#### 🤔 Expected Behavior

Node should reject transaction and continue its execution.

#### 😯 Current Behavior

Node just panics.

#### 🖥️ Environment

- **Rust version**: 1.68.0
- **Operating System & Version**: Mac OS Monterey 12.6.5

#### 📎 Log Output

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ValidationFailed(General { msg: "Not enough balance for fee + value", data: [8, 195, 121, 160, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 34, 78, 111, 116, 32, 101, 110, 111, 117, 103, 104, 32, 98, 97, 108, 97, 110, 99, 101, 32, 102, 111, 114, 32, 102, 101, 101, 32, 43, 32, 118, 97, 108, 117, 101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] })', src/node.rs:366:60
```

**Comment by MexicanAce** [comment]
Thanks for the issue @vladbochok ! We're tracking to address this issue by having better error handling and stopping the use of `unwrap()`. Should be resolved within the next week.

**Comment by MexicanAce** [comment]
This was addressed in https://github.com/matter-labs/era-test-node/pull/24
