### ISSUE TITLE
Cleaner detection of out-of-gas situations

### ISSUE THREAD

**Issue by mm-zk** [matter-labs/era-test-node#239]
#### 📝 Description

Currently, when contract runs out of gas, you can see the 'panic' message, but you don't know the reason. It would be great if we passed the clear information that this was caused by out of gas.

#### 🤔 Rationale

This will make debugging a lot easier.

#### 🖼️ Mockups/Examples
<img width="797" alt="image" src="https://github.com/matter-labs/era-test-node/assets/128217157/dabe1102-1c1b-4dfa-a423-38d92178dc72">
This should say 'out of gas' instead of 'only' Panic.

#### 📋 Additional Context

You can fetch the panic reason from the error_flags.
Here's the (very dirty) example, how this could work:
https://github.com/matter-labs/era-test-node/commit/8338df656c87860ce4fb6ded2bcd3050e9941f83
We should probably move it either into CallTracer - or create a separate tracer just for era test node to catch and print this information.

**Comment by MexicanAce** [comment]
Resolved with #311
