### ISSUE TITLE
operatorID Rate Limit Exceeded

### ISSUE THREAD

**Issue by wnhedaxx** [matter-labs/era-test-node#263]
When I run
./run.sh opt-in

Error occured like below.
error: failed to request churn approval: rpc error: code = Unknown desc = rate limiter error: operatorID Rate Limit Exceeded:

I'm first time running node.
I don't know why ma Rate Limit Exceeded.

**Comment by MexicanAce** [comment]
We don't have a run.sh script in our repo. Perhaps this was meant for another GitHub project?
