### ISSUE TITLE
fix:`evm_setNextBlockTimestamp` to return timestamp not in hex format  

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#273]
#### 📝 Description

Currently `evm_setNextBlockTimestamp` returns timestamp in a hex format. 

#### 🔄 Reproduction Steps

1. Make curl request to `evm_setNextBlockTimestamp` 

#### 🤔 Expected Behavior

Should return timestamp as:

```
{
  "jsonrpc": "2.0",
  "result": 1750074671,
  "id": "1234"
}
```

#### 😯 Current Behavior

Currently `evm_setNextBlockTimestamp` returns timestamp in a hex format. 

```
{
  "jsonrpc": "2.0",
  "result": '0x6850052f',
  "id": "1234"
}
```

#### 🖥️ Environment

- **Rust version**: [e.g., rustc 1.52.0]
- **Operating System & Version**: [e.g., Ubuntu 20.04]
- **Other relevant environment details**:

#### 📋 Additional Context

Add any other context about the problem here. If applicable, add screenshots to help explain.

#### 📎 Log Output

```
Paste any relevant log output here.
```

**Comment by MexicanAce** [comment]
This is resolved
