### ISSUE TITLE
fix `eth_getBlockByNumber` to return timestamp in seconds not milliseconds 

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#274]
#### 📝 Description

`eth_getBlockByNumber` - called on era-test-node returns block with timestamp entry that is in milliseconds. Hardhat in tests works in seconds, which means that in order to work for zkSync, a multiplication of 1000 is required.

#### 🤔 Expected Behavior

Return timestamp in seconds rather than milleseconds. 

#### 😯 Current Behavior

Returns timestamp in seconds.

**Comment by MexicanAce** [comment]
This is resolved
