### ISSUE TITLE
Failed eth_sendTransaction on forked mainnet

### ISSUE THREAD

**Issue by teamspice** [matter-labs/era-test-node#278]
please see https://github.com/zkSync-Community-Hub/zksync-developers/discussions/390

using 0xE999bb14881e48934A489cC9B35A4f9449EE87fb as the from address, and adding a call to hardhat_impersonateAccount with 0xE999bb14881e48934A489cC9B35A4f9449EE87fb as the input parameter, the error I am receiving is:

Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"error\":{\"code\":3,\"message\":\"Execution error: Transaction HALT: virtual machine entered unexpected state. Please contact developers and provide transaction details that caused this error. Error description: Assertion error: Overhead higher than gasLimit\",\"data\":\"0x3fafbf289f1134f1a0d3e6efc05d2e33475d4453edc435a587b3525ecb15977f\"},\"id\":51}\n", error={"code":3,"data":"0x3fafbf289f1134f1a0d3e6efc05d2e33475d4453edc435a587b3525ecb15977f"}, requestBody="{\"method\":\"eth_sendTransaction\",\"params\":[{\"to\":\"0x3355df6d4c9c3035724fd0e3914de96a5a83aaf4\",\"value\":\"0x0\",\"data\":\"0xa9059cbb00000000000000000000000042310121982db7fa65552ae797016ab63b4302920000000000000000000000000000000000000000000000000000000000989680\",\"from\":\"0xE999bb14881e48934A489cC9B35A4f9449EE87fb\",\"maxFeePerGas\":\"0x5c631f80\",\"maxPriorityFeePerGas\":\"0x59682f00\",\"gasLimit\":\"100000000000000\"}],\"id\":51,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="", code=SERVER_ERROR, version=web/5.7.1)

**Comment by MexicanAce** [comment]
Hi @teamspice ! This is now fixed in the latest `0.1.0-alpha.24` release. Thank you for reporting!
