### ISSUE TITLE
[FEAT]: Introduce dynamic gas param fetching

### ISSUE THREAD

**Issue by dutterbutter** [matter-labs/era-test-node#279]
#### 📝 Description

Currently gas params are static [here](https://github.com/matter-labs/era-test-node/blob/de98cebbb85264224019e0923b29da125967d803/src/node/in_memory.rs#L84), and [here](https://github.com/matter-labs/era-test-node/blob/main/src/node/fee_model.rs#L6). These parameters change, and require manually updates. These should be dynamically fetched. 

#### 🤔 Rationale

Gas params should be dynamic so it accurately resembles mainnet / testnet. These params change over time and are currently outdated. This is important for adequately testing and debugging applications.

**Comment by MexicanAce** [comment]
This is now resolved with Release `0.1.0-alpha.24`. When forking an upstream network, various gas params and gas estimation variables are dynamically configured. These values are also overridable just incase a specific gas param needs to be configured for testing purposes.
