### ISSUE TITLE
Impersonate Account Doesn't Execute Transaction In Context Of Impersonated Account

### ISSUE THREAD

**Issue by bonedaddy** [matter-labs/era-test-node#281]
#### 📝 Description

The impersonate account functionality does not appear to execute a transaction setting `msg.sender` to the impersonated account.

#### 🤔 Expected Behavior

Transaction passes having executed the transaction setting `msg.sender` to the impersonated account

#### 😯 Current Behavior

Transaction reverts having executed the transaction with `msg.sender` set to the account I'm signing the transaction with 

#### 🖥️ Environment

* era_test_node version `era_test_node 0.1.0-alpha.1`

#### 📎 Log Output

As per the followingloutput, the transaction fails with the call graph having been executed from the `initiator` account, as opposed to the account that I impersonated.

```
========================================
  Node is ready at 127.0.0.1:8011
========================================
🕵️ Account 0x69f33e02555b0634beef0406f99cc7f632b13891 has been impersonated

Validating 0xf7c0bbd0b55ecd4f1f7ed0b01b62f5685848e00828b852acbfa4f38081647a62
Executing 0xf7c0bbd0b55ecd4f1f7ed0b01b62f5685848e00828b852acbfa4f38081647a62
┌─────────────────────────┐
│   TRANSACTION SUMMARY   │
└─────────────────────────┘
Transaction: FAILED
Initiator: 0xbc989fde9e54cad2ab4392af6df60f04873a033a
Payer: 0xbc989fde9e54cad2ab4392af6df60f04873a033a
Gas - Limit: 2_500_000 | Used: 461_380 | Refunded: 2_038_620

Call(Normal) 0xbc989fde9e54cad2ab4392af6df60f04873a033a                   df9c1589  Revert: caller not whitelist setter or owner  2012850
  Call(Normal) 0x2d621b6453de839cb37acf35c5934811b933cc09                   c32d5564  Revert: caller not whitelist setter or owner  1970073
```

**Comment by MexicanAce** [comment]
Thank you for the report @bonedaddy ! Do you have any example script we could have to test this out?

We (in theory) have e2e tests to cover this scenario here : https://github.com/matter-labs/era-test-node/blob/main/e2e-tests/test/hardhat-apis.test.ts#L68

Perhaps with your additional example, we can see where the difference is and troubleshoot further

**Comment by MexicanAce** [comment]
Closing issue as stale
