### ISSUE TITLE
[FEAT]: simple installation script - like rustup

### ISSUE THREAD

**Issue by mm-zk** [matter-labs/era-test-node#299]
#### 📝 Description

Create simple installation script that would autodetect the current OS, download the latest era-test-node and do the setup (similar to rustup)

#### 🤔 Rationale

Makes it easier for the users.

#### 📋 Additional Context

The base minimum is to download the latest era-test-node. Bonus points if it could also manage multiple versions (similar to rust).

**Comment by MexicanAce** [comment]
For awareness, this is already covered with `npx zksync-cli dev start`
