### ISSUE TITLE
zks_estimateFee test fails when run standalone

### ISSUE THREAD

**Issue by vbar** [matter-labs/era-test-node#320]
#### 📝 Description

Specifically the "Should return fee estimation data for transfer of 1 ETH" clause gets unexpected values. The test passes (as all tests pass) when run through `make test-e2e`.

#### 🔄 Reproduction Steps

Run era test node as if for e2e tests, but instead of running all tests, switch to the `e2e-tests` directory and run `npx hardhat test --grep zks_estimateFee`.

#### 🤔 Expected Behavior

The test should pass.

#### 🖥️ Environment

- **Rust version**: nightly-2024-01-01, as specified in `rust-toolchain.toml`
- **Operating System & Version**: Ubuntu 20.04.6

#### 📋 Additional Context

The interference is apparently from the "hardhat_impersonateAccount & hardhat_stopImpersonatingAccount" test, which switches system contracts to their impersonating variant (and doesn't call `hardhat_stopImpersonatingAccount` to switch them back), which probably affects fee calculations.

#### 📎 Log Output
'''
e2e-tests$ npx hardhat test --grep zks_estimateFee

  zks_estimateFee
    1) Should return fee estimation data for transfer of 1 ETH

  0 passing (158ms)
  1 failing

  1) zks_estimateFee
       Should return fee estimation data for transfer of 1 ETH:

      Unexpected gas_limit
      + expected - actual

       {
      -  "_hex": "0x598cb8"
      +  "_hex": "0x3708d7"
         "_isBigNumber": true
       }
      
      at Context.<anonymous> (test/zks-apis.test.ts:33:58)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by MexicanAce** [comment]
Resolved in #313
