### ISSUE TITLE
eth_getCode returns code hash instead of code

### ISSUE THREAD

**Issue by vladbochok** [matter-labs/era-test-node#33]
#### 📝 Description

`eth_getCode` endpoint returns bytecode hash, not the raw bytecode. 

#### 🔄 Reproduction Steps

1. Make `eth_getCode` API request for `0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee` address (random one)
2. The returned value will be `0x0000000000000000000000000000000000000000000000000000000000000000`

#### 🤔 Expected Behavior

The expected value should be empty bytes - `0x` since the address should not contain any bytecode.

#### 😯 Current Behavior

Currently the method returns bytecode hash.

#### 🖥️ Environment

- **Rust version**: 1.68.0
- **Operating System & Version**: Mac OS Monterey 12.6.5

#### 📋 Additional Context

Returning bytecode hash instead of bytecode breaks specific tests for some contracts, for example, to check whether the address is EOA or contract one can check that `eth_getCode` returned value is empty bytes.

**Comment by MexicanAce** [comment]
Fixed in https://github.com/matter-labs/era-test-node/pull/59
