### ISSUE TITLE
[FEAT] Generate some empty blocks to make era-test-node work nicer with wallets like metamask 

### ISSUE THREAD

**Issue by mm-zk** [matter-labs/era-test-node#334]
#### 📝 Description

If you use your metamask wallet with era-test-node, the transactions might show up as 'pending'. 
This is due to the fact that era-test-node is generating new blocks only when a new transaction shows up, and meta-mask is waiting (by default) for the next block before even checking if transaction was executed.

There are 2 solutions:
* have era-test-node generate a block every couple seconds - it is simple solution, but will create potentially a bunch of noise in the logs etc.
* or - have era-test-node create an empty block after couple seconds, only if the previous block was non-empty - while this is a little bit more complex, it means that if you send a transaction (and then do nothing), test node would still generate an empty block, which should help wallets like metamask to correctly mark the transaction as completed.

**Comment by MexicanAce** [comment]
I think this would require support of something like [Mining Modes from Hardhat](https://hardhat.org/hardhat-network/docs/reference#mining-modes).

My preference would be to keep things simple and go with the first option: `generate a block every couple of seconds` and make this optional while keeping the noise in the logs to a minimum
