### ISSUE TITLE
Enable node responses to have variable length

### ISSUE THREAD

**Issue by IAvecilla** [matter-labs/era-test-node#34]
#### 📝 Description

The node should be able to return responses of arbitrary length. Currently, the node always returns vectors with a length that is a multiple of 32 achieved by padding the original results with zeros.

#### 🤔 Rationale

For the correct implementation of certain precompiles, it's necessary to have responses with variable lengths. According to [EIP198](https://eips.ethereum.org/EIPS/eip-198), which introduces the precompile specification, the precompile should return a byte array with a length matching the modulus length. However, due to the current behavior , it's impossible to comply with the specification.

Furthermore, this change would align with the approach taken by the L1 node, ensuring consistency with EVM behavior.

#### 📋 Additional Context

Here are examples that compare the results from the L1 node with the outputs when using the local node with a `modexp` implementation:

```
L1 and L2 inputs: 
0000000000000000000000000000000000000000000000000000000000000001
0000000000000000000000000000000000000000000000000000000000000001
0000000000000000000000000000000000000000000000000000000000000001
02
03
00
```

```
L1 output: Bytes(0x00)
L2 output: Bytes(0x0000000000000000000000000000000000000000000000000000000000000000)
```

In this case, L1 returns only 1 byte with a value of 0. Our precompile does the same, but the VM right-pads the result with zeros to extend it to 32 bytes.

```
L1 and L2 inputs:
0000000000000000000000000000000000000000000000000000000000000001
0000000000000000000000000000000000000000000000000000000000000001
0000000000000000000000000000000000000000000000000000000000000001
02 
00 
04
```

```
L1 output: Bytes(0x01)
L2 output: Bytes(0x0100000000000000000000000000000000000000000000000000000000000000)
```

Similarly, in this example, the result is 1. However, the expected outcome should correspond only to the first two digits (1 byte). The result is right-padded with zeros to extend it to 32 bytes, resulting in a completely different number.

**Comment by MexicanAce** [comment]
This issue was resolved upstream in `zksync-era` and is available as of the latest release of `era-test-node`
