### ISSUE TITLE
`config_setResolveHashes` breaks era_test_node

### ISSUE THREAD

**Issue by bxpana** [matter-labs/era-test-node#345]
#### 📝 Description

- I tried adding `config_setResolveHashes` from the [docs](https://docs.zksync.io/build/test-and-debug/in-memory-node#replay-remote-transactions-locally) and it broke my test node so I had to restart it.  

#### 🔄 Reproduction Steps

1. `era_test_node run` 
2. 
```
curl --request POST \
  --url http://localhost:8011/ \
  --header 'content-type: application/json' \
  --data '{"jsonrpc": "2.0","id": "1","method": "config_setResolveHashes","params": [true]}'
```

#### 🤔 Expected Behavior

era_test_node continues to run without issues 

#### 😯 Current Behavior

era_test_node crashes and I have to restart

#### 🖥️ Environment

- **Rust version**: rustc 1.81.0
- **Operating System & Version**: MacOS M3 Max
- **Other relevant environment details**:

#### 📋 Additional Context

Add any other context about the problem here. If applicable, add screenshots to help explain.

#### 📎 Log Output

  - error after adding `config_setResolveHashes`:
  ```
   17:56:09  WARN spurious network detected for sig.eth.samczsun.com
  thread '<unnamed>' panicked at src/formatter.rs:160:80:
  called `Result::unwrap()` on an `Err` value: error sending request for url (https://sig.eth.samczsun.com/api/v1/signatures?function=0x70a08231): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known

  Caused by:
   0: error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
   1: dns error: failed to lookup address information: nodename nor servname provided, or not known
   2: failed to lookup address information: nodename nor servname provided, or not known

  Location:
    src/resolver.rs:166:19
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  thread 'tokio-runtime-worker' panicked at src/fork.rs:58:6:
  called `Result::unwrap()` on an `Err` value: Any { .. }
  ```

**Comment by MexicanAce** [comment]
@bxpana This should be resolved with https://github.com/matter-labs/era-test-node/pull/342
