### ISSUE TITLE
feat: implement `anvil_setMinGasPrice` API endpoint

### ISSUE THREAD

**Issue by itegulov** [matter-labs/era-test-node#434]
A method that sets pre-EIP1559 minimum gas price accepted by the network:
```rust
#[rpc(name = "anvil_setMinGasPrice")]
fn set_min_gas_price(&self, gas: U256) -> RpcResult<()>;
```

**Comment by itegulov** [comment]
Given that this is intended to only be used for pre-EIP1559 chains I propose we return `RpcUnimplemented` with an explanation why using this method does not make sense.

A reasonable alternative would be to set `l2_gas_price` to the provided value but I kind of feel like we should just create our own namespace to manipulate ZKsync-specific gas config (and other things in general).

@popzxc WDYT?

**Comment by popzxc** [comment]
@itegulov I'm OK with having `RpcUniplemented` for now -- if someone needs it, they will open an issue and we will discuss a particular use case.
