### ISSUE TITLE
Gas Limit Error with VM Entering Unexpected State

### ISSUE THREAD

**Issue by idea404** [matter-labs/era-test-node#84]
#### 📝 Description

When using the binary released with `v0.1.0` a paymaster test fails with:

```bash
 Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"reason":"execution reverted: virtual machine entered unexpected state. Please contact developers and provide transaction details that caused this error. Error description: Assertion error: paymaster non zero","code":"UNPREDICTABLE_GAS_LIMIT","method":"estimateGas"
 ```

This error was initially reported by @zzomrot. For tests repository: [paymaster-zksync](https://github.com/1inch/paymaster-zksync) with this description:

> When I build the node using the commit 4ef5a96ec1525040f920f0a892d238e76529af23 with the following command:
> 
> `cargo install --git https://github.com/matter-labs/era-test-node.git --rev 4ef5a96ec1525040f920f0a892d238e76529af23 --locked`
> 
> and subsequently run the tests in the repo, I encounter an error:
> 
> `Observed error that should never happen: VmRevertReasonParsingResult { revert_reason: UnexpectedVMBehavior("Assertion error: paymaster non zero"), original_data: …`
> 
> However, when I use the previous commit `3539ad0a87f5cc5350b346bace874f4d966714b3`, the tests pass without issue

#### 🔄 Reproduction Steps

1. Clone either repo and run the CI steps

Or to follow @zzomrot steps, run the tests from his repo then create a dir to save the Dockerfile and start_script.sh files and adapt the Dockerfile --rev param to: 4ef5a96ec1525040f920f0a892d238e76529af23

Dockerfile
```
FROM rust:latest

RUN apt-get update && apt-get install -y cmake pkg-config libssl-dev clang socat

RUN cargo install --git https://github.com/matter-labs/era-test-node.git --rev 3539ad0a87f5cc5350b346bace874f4d966714b3 --locked

COPY start_script.sh /start_script.sh

RUN chmod +x /start_script.sh

ENTRYPOINT ["/start_script.sh"]
```

start_script.sh
```
#!/bin/bash

ARG1_DEFAULT="8011"
ARG2_DEFAULT="mainnet"

PORT="${1:-$ARG1_DEFAULT}"
NETWORK="${2:-$ARG2_DEFAULT}"

socat TCP-LISTEN:"$PORT",fork,reuseaddr TCP:127.0.0.1:3051 &
era_test_node --port 3051 fork "$NETWORK" &
wait
```

#### 🤔 Expected Behavior

Test to pass. 

#### 😯 Current Behavior

Error.

Full Error Message:

https://github.com/idea404/paymaster-zksync/actions/runs/5951030825/job/16140118097

**Comment by MexicanAce** [comment]
@idea404 Are we able to replicate this against testnet? Want to rule out that the issue is not related to contract factory code in the paymaster-zksync repo.

For awareness, the gas estimation was updated after the `3539ad0a87f5cc5350b346bace874f4d966714b3` commit on `main`. Using that commit has the hard-coded implementation, which isn't actually estimating gas fees.

**Comment by idea404** [comment]
Closing this issue as error also occurred on testnet and is thus not related to `era-test-node`.
